Repository JianHui97/SemProject, pull requests merged in 2020-07, with the labels that each got.

#27 modified design
  sdw/ManageBooth/View/BoothForm.php
Labels: enhancement

#30 Addbutton
  sdw/ManageBooth/View/BoothForm.php
Labels: enhancement

#31 fixed booth view
  sdw/ManageBooth/View/BoothView.php
Labels: bug, enhancement

#32 add addequip file
  sdw/ManageEquipment/addequip.php
Labels: addfile

#33 Modify evaluation form
  sdw/ManageBooth/View/BoothForm.php
  sdw/ManageBooth/View/BoothView.php
  sdw/ManageEquipment/addequip.php
Labels: enhancement

#34 Update addequip.php
  sdw/ManageEquipment/addequip.php
Labels: bug, enhancement

#35 change evaluation form
  sdw/ManageEvaluation/view/EvaluationForm.php
Labels: enhancement

#36 add button for evaluation page
  sdw/ManageEvaluation/view/header.html
Labels: bug, enhancement

#37 add view equip file
  sdw/ManageEquipment/viewequip.php
Labels: addfile, documentation

#38 add booking equip
  sdw/ManageEquipment/bookequip.php
Labels: addfile

#39 Equip p2
  sdw/ManageEquipment/cart.php
  sdw/ManageEquipment/reserveequip.php
Labels: addfile

#42 Equip p4
  sdw/ManageEquipment/bookequip.php
  sdw/ManageEquipment/deletebook.php
  sdw/ManageEquipment/editbook.php
Labels: bug, enhancement

#41 insert edit book
  sdw/ManageEquipment/editbook.php
Labels: addfile

#40 create new header for evaluationForm page
  sdw/ManageEvaluation/view/header2.html
Labels: addfile, enhancement

#43 modified cart and reserve
  sdw/ManageEquipment/cart.php
  sdw/ManageEquipment/reserveequip.php
Labels: bug, enhancement

#44 Participant Header
  sdw/ManageLogin/View/pheader.php
Labels: bug, enhancement

#45 fix error in delete and edit
  sdw/ManageEquipment/deletebook.php
  sdw/ManageEquipment/editbook.php
Labels: bug, enhancement

#49 modified view equip
  sdw/ManageEquipment/viewequip.php
Labels: bug, enhancement

#53 add edit equip file
  sdw/ManageEquipment/editequip.php
Labels: documentation

#55 ManageFiles
  sdw/ManageEquipment/addequip.php
  sdw/ManageEquipment/bookequip.php
  sdw/ManageEquipment/cart.php
  sdw/ManageEquipment/deletebook.php
  sdw/ManageEquipment/editbook.php
  sdw/ManageEquipment/editequip.php
  sdw/ManageEquipment/reserveequip.php
  sdw/ManageEquipment/viewequip.php
Labels: documentation

#57 Update ParticipantProfile.php
  sdw/ManageLogin/View/ParticipantProfile.php
Labels: bug

#54 Update header3.php
  sdw/ManageLogin/View/header3.php
Labels: bug, enhancement

#48 Update header1.php
  sdw/ManageLogin/View/header1.php
  sdw/ManageLogin/View/header2.php
Labels: bug

#59 add model
  sdw/ManageEquipment/library/config.php
  sdw/ManageEquipment/library/database.php
  sdw/ManageEquipment/model/equipment_model.php
  sdw/ManageEquipment/model/manage_equipment_model/manage_equipment_model.php
  sdw/ManageEquipment/model/reserve_model.php
Labels: addfile

#60 edit the tab
  sdw/ManageBooth/View/header1.php
Labels: duplicate

#61 update addequip
  sdw/ManageEquipment/manage_equipment/addequip.php
Labels: enhancement

#63 manage equipment controller files
  sdw/ManageEquipment/controller/equipment_con.php
  sdw/ManageEquipment/controller/reserve_con.php
Labels: documentation

#64 modified deleteequip
  sdw/ManageEquipment/manage_equipment/deleteequip.php
Labels: enhancement

#62 adding Model
  sdw/ManagePayment/Model/Libs/Payment_Detail_Config.php
  sdw/ManagePayment/Model/Libs/Payment_Detail_Database.php
  sdw/ManagePayment/Model/Payment_Detail_Model.php
  sdw/ManagePayment/Model/Payment_Form_Model.php
  sdw/ManagePayment/Model/Payment_Receipt_Model.php
  sdw/ManagePayment/View/Payment_Form.php
Labels: addfile

#66 edit editequip
  sdw/ManageEquipment/manage_equipment/editequip.php
Labels: enhancement

#67 payment
  sdw/ManageBooth/View/header1.php
  sdw/ManageEquipment/controller/equipment_con.php
  sdw/ManageEquipment/controller/reserve_con.php
  sdw/ManageEquipment/manage_equipment/addequip.php
  sdw/ManageEquipment/manage_equipment/deleteequip.php
  sdw/ManageEquipment/manage_equipment/editequip.php
Labels: bug

#68 Payment
  sdw/ManagePayment/Model/Payment_Detail_Model.php
  sdw/ManagePayment/View/Payment_Detail.php
Labels: enhancement

#69 edited viewequip
  sdw/ManageEquipment/manage_equipment/viewequip.php
Labels: bug, enhancement

#70 Payment
  sdw/ManagePayment/View/Payment_Detail.php
Labels: enhancement

#71 payment
  sdw/ManageEquipment/manage_equipment/viewequip.php
Labels: bug

#72 Payment
  sdw/ManagePayment/Controller/Payment_Controller.php
Labels: enhancement

#73 fix bug
  sdw/ManagePayment/Model/Payment_Detail_Model.php
Labels: bug
